### ISSUE TITLE
Portuguese Translation 

### ISSUE THREAD

**Issue by MarceloDuaarte** [bookfere/Ebook-Translator-Calibre-Plugin#205]
Hello. I would like to note here that the translation carried out by the plugin when the target language is Portuguese, ends up mixing Brazilian Portuguese with European Portuguese.

I'm trying to translate some ebooks into Brazilian Portuguese, but when checking some excerpts, I realize that they contain words typically from European Portuguese. The words in Brazilian Portuguese "moça/jovem/garota" which in English would be "young girl/girl" are translated as "rapariga" , which is a European Portuguese word. However, this word has a very negative connotation in Brazilian Portuguese, which ends up making the translation very confusing.

Some sentences end up having a typically European Portuguese construction, for example.

"The kid is playing" in English ends up being translated as "A criança está a brincar", which is how it is said in good European Portuguese, while in Brazilian Portuguese we would say "A criança está brincando". The construction of the sentence ends up making the text strange, as it mixes the two.

You can't help but notice that when the file translation is finished, the file receives [Portuguese - Brazil-Portugal] at the end of its name. Which leaves me with more doubts as to whether the translation engine is independent for the two languages, as they are different, very different.

I love your tool, and I don't want to seem ungrateful, but this type of situation makes it somewhat irritating to use when reading, as it mixes the two languages as if they were one.

The mechanism I used was Google Translator. However, when I access the translation engine website, it translates into Brazilian Portuguese correctly, without mixing the two languages.

I await a return.

**Comment by bookfere** [comment]
There is only a single language code for Portuguese in the Google Translate [language support list](https://cloud.google.com/translate/docs/languages):

|Language |ISO-639 code|
|---|---|
|Portuguese (Portugal, Brazil) | pt|

I used the simple phrase you provided, "The kid is playing," for testing, either in the plugin or on the Google Translate website (translate.google.com and translate.google.pt), and the result is "A criança está brincando."

According to discussions I found on the Google Translate Community ([1](https://support.google.com/translate/thread/50580591?sjid=832357712575047105-AP), [2](https://support.google.com/translate/thread/51414150/european-portuguese?hl=en), [3](https://support.google.com/translate/thread/114837133/why-does-google-translate-provide-brazilian-portuguese-pronunciation-only?hl=en), [4](https://support.google.com/translate/thread/114837133/why-does-google-translate-provide-brazilian-portuguese-pronunciation-only?hl=en)), it's likely that the translation result provided by Google Translate defaults to Brazilian Portuguese rather than European Portuguese.

I do not know, however, why you got an inconsistent result with the Google Translate API and website. Maybe you can consider posting the problem on the [Google Translate Community](https://support.google.com/translate/community?hl=en) for confirmation.
