### ISSUE TITLE
UnBoundLocalError

### ISSUE THREAD

**Issue by thoughtfission** [bookfere/Ebook-Translator-Calibre-Plugin#234]
**Basic information**
Some required information from your use case.

* Operating System: **Windows**
* Calibre Version: **latest**
* Plugin Installation: **From Calibre Latest Stable**

**Describe the bug**
calibre, version 7.7.0
ERROR: Unhandled exception: <b>UnboundLocalError</b>:cannot access local variable 'metadata' where it is not associated with a value

calibre 7.7  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre.exe
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 9, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (2, 9, 0) && Annotations (1, 17, 13) && Ebook Translator (2, 3, 1) && Find Duplicates (1, 10, 8) && KFX metadata reader (from KFX Input) (2, 9, 0) && From KFX (2, 9, 0) && KFX Input (2, 9, 0) && Set KFX metadata (from KFX Output) (2, 7, 0) && KFX Output (2, 7, 0) && Kindle Collections (1, 7, 29) && Kindle hi-res covers (0, 5, 1) && Obok DeDRM (7, 2, 1)
Traceback (most recent call last):
  File "calibre\gui2\__init__.py", line 756, in dispatch
  File "calibre_plugins.ebook_translator.lib.conversion", line 269, in translate_done
UnboundLocalError: cannot access local variable 'metadata' where it is not associated with a value

**Expected behavior**
Trying to save the translated doc and I get this error.

**Screenshots**
See above

**Comment by Givemeaccesss** [comment]
calibre, version 7.7.0
ERRORE: Eccezione non gestita: <b>UnboundLocalError</b>:cannot access local variable 'metadata' where it is not associated with a value

calibre 7.7  embedded-python: True
Windows-10-10.0.22635-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22635')
Python 3.11.5
Windows: ('10', '10.0.22635', 'SP0', 'Multiprocessor Free')
Interface language: it
EXE path: C:\Program Files\Calibre2\calibre.exe
Successfully initialized third party plugins: Ebook Translator (2, 3, 0) && Kobo Metadata (1, 5, 0)
Traceback (most recent call last):
  File "calibre\gui2\__init__.py", line 756, in dispatch
  File "calibre_plugins.ebook_translator.lib.conversion", line 262, in translate_done
UnboundLocalError: cannot access local variable 'metadata' where it is not associated with a value

It gave me the same error even on 2.3.0 version, i think the problem is the main calibre software last version.

**Comment by bookfere** [comment]
Thank you for your feedback. We have fixed the issue in version 2.3.2. Please upgrade from Calibre and check if the issue has disappeared. If not, feel free to provide further feedback.

**Comment by Givemeaccesss** [comment]
Now it's perfectly fixed , thank you

Carmine Morcone

Il sab 16 mar 2024, 07:15 书伴 ***@***.***> ha scritto:
