### ISSUE TITLE
Cannot Connect Deepl Pro to Calibre for translation

### ISSUE THREAD

**Issue by jamadun** [bookfere/Ebook-Translator-Calibre-Plugin#304]
hello, i have purchased subscription DeepL Pro advanced + DeepL write pro and i got the API Keys ofcourse.

but why i cant connect API keys from DeepL Pro to Calibre?

![Screen Shot 2024-05-10 at 7 38 10 AM](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/169412078/2914fdb5-be40-4bba-b28f-4b48c35f9a94)

**Comment by bookfere** [comment]
As the error information hinted, you do not have permission to access the API. The reason is that the "DeepL Pro" plan is different from the "DeepL API" plan; only the latter can be used in the plugin. If you have any confusion about these two plans, I recommend you contact DeepL's customer service.
