### ISSUE TITLE
Save of Setting not works

### ISSUE THREAD

**Issue by remark3d** [bookfere/Ebook-Translator-Calibre-Plugin#87]
Your Calibre plugin is absolutely brilliant and thank you so much for it!

Some of the translations are so good that I don't need to have both versions of the language in the book, the translated one is enough. I see that in the settings there is this option, but unfortunately even if the settings are saved, the program does not accept the settings, it seems that after saving and closing the settings window, the "settings" returns to the default state (reset), when the settings are reopened, it is again in the default state. Is this error just me, or should I wait for an update?

There is also a problem with storage. The file with the translated book is opened correctly, but later in the place of saving there is only a file with the title of the book (text) without a suffix (extension/format) and size 0kB

The original translated file cannot be found at all, although it can be opened after translation, it is not placed in the right place and I could not find where the plugin saves this file by default, it is probably somewhere only in cash.

Thank you very much and have a nice day
Martin

**Comment by wangshuihua** [comment]
I am glad you like the plugin. The bug of setting saving was solved in latest version (v2.1.1).

As for the second issue, unfortunately I can not duplicate the storage problem you reported. We suspect it is related to some temporary file removing schedule of **Windows** system. Since this only happens when translated book saved in Calibre **Library**,  you may need to check the setting of Output Path to confirm it was set as Library. 

If that is the case, you may try to turn off the Storage Sense of system setting or give Calibre a dedicated directory for its temporary files via the **CALIBRE_TEMP_DIR** Environment variable, as specified [here](https://www.mobileread.com/forums/showpost.php?p=4311779&postcount=11) in detail.

**Comment by remark3d** [comment]
Hi,

Thank you very much for the really quick response and update. I tried it
today and the "setting" is saved and is functional.

Thanks for the information about saving, it looks like the problem is on my
PC, I will try to solve it myself.

Thank you again very much and I wish you a lot of working success!
Martin

ne 16. 7. 2023 v 5:58 odesílatel Sherry ***@***.***> napsal:

**Comment by Lasse73** [comment]
Thank you very much for this addon. This is just brilliant. Nice work
